package neu.edu.entity;
// Generated Dec 15, 2016 5:29:54 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * AdminTable generated by hbm2java
 */
public class AdminTable implements java.io.Serializable {

	private int adminId;
	private String usertype;
	private String username;
	private String password;
	private int personid;

	public AdminTable() {
	}

	public AdminTable(int adminId, String usertype, String username, String password, int personid) {
		this.adminId = adminId;
		this.usertype = usertype;
		this.username = username;
		this.password = password;
		this.personid = personid;
	}

	public int getAdminId() {
		return this.adminId;
	}

	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getPersonid() {
		return this.personid;
	}

	public void setPersonid(int personid) {
		this.personid = personid;
	}

}
