package neu.edu.entity;
// Generated Dec 15, 2016 5:29:54 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * CustomerTable generated by hbm2java
 */
public class CustomerTable implements java.io.Serializable {

	private int customerId;
	private String usertype;
	private String username;
	private String password;
	private String status;
	private int personId;

	public CustomerTable() {
	}

	public CustomerTable(int customerId, String usertype, String username, String password, String status,
			int personId) {
		this.customerId = customerId;
		this.usertype = usertype;
		this.username = username;
		this.password = password;
		this.status = status;
		this.personId = personId;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

}
