package neu.edu.entity;
// Generated Dec 15, 2016 5:29:54 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * OrderProductTable generated by hbm2java
 */
public class OrderProductTable implements java.io.Serializable {

	private int orderProductTableId;
	private int orderId;
	private int productId;

	public OrderProductTable() {
	}

	public OrderProductTable(int orderProductTableId, int orderId, int productId) {
		this.orderProductTableId = orderProductTableId;
		this.orderId = orderId;
		this.productId = productId;
	}

	public int getOrderProductTableId() {
		return this.orderProductTableId;
	}

	public void setOrderProductTableId(int orderProductTableId) {
		this.orderProductTableId = orderProductTableId;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

}
