package neu.edu.entity;
// Generated Dec 15, 2016 5:29:54 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * PaymentInformationTable generated by hbm2java
 */
public class PaymentInformationTable implements java.io.Serializable {

	private int paymentId;
	private String cardType;
	private String cardNumber;
	private String nameOnCard;
	private String expiryDate;
	private Integer cvv;
	private Integer customerId;

	public PaymentInformationTable() {
	}

	public PaymentInformationTable(int paymentId) {
		this.paymentId = paymentId;
	}

	public PaymentInformationTable(int paymentId, String cardType, String cardNumber, String nameOnCard,
			String expiryDate, Integer cvv, Integer customerId) {
		this.paymentId = paymentId;
		this.cardType = cardType;
		this.cardNumber = cardNumber;
		this.nameOnCard = nameOnCard;
		this.expiryDate = expiryDate;
		this.cvv = cvv;
		this.customerId = customerId;
	}

	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	public String getNameOnCard() {
		return this.nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	public Integer getCvv() {
		return this.cvv;
	}

	public void setCvv(Integer cvv) {
		this.cvv = cvv;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

}
