package neu.edu.entity;
// Generated Dec 15, 2016 5:29:54 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private int personId;
	private String title;
	private String firstname;
	private String lastname;
	private String emailid;
	private String dob;
	private String occupationtype;

	public Person() {
	}

	public Person(int personId) {
		this.personId = personId;
	}

	public Person(int personId, String title, String firstname, String lastname, String emailid, String dob,
			String occupationtype) {
		this.personId = personId;
		this.title = title;
		this.firstname = firstname;
		this.lastname = lastname;
		this.emailid = emailid;
		this.dob = dob;
		this.occupationtype = occupationtype;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getOccupationtype() {
		return this.occupationtype;
	}

	public void setOccupationtype(String occupationtype) {
		this.occupationtype = occupationtype;
	}

}
