package neu.edu.entity;
// Generated Dec 15, 2016 5:29:54 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * ProductTable generated by hbm2java
 */
public class ProductTable implements java.io.Serializable {

	private int productId;
	private String modelNo;
	private String category;
	private String name;
	private Integer price;
	private String color;
	private Integer sellerId;

	public ProductTable() {
	}

	public ProductTable(int productId) {
		this.productId = productId;
	}

	public ProductTable(int productId, String modelNo, String category, String name, Integer price, String color,
			Integer sellerId) {
		this.productId = productId;
		this.modelNo = modelNo;
		this.category = category;
		this.name = name;
		this.price = price;
		this.color = color;
		this.sellerId = sellerId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getModelNo() {
		return this.modelNo;
	}

	public void setModelNo(String modelNo) {
		this.modelNo = modelNo;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Integer getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(Integer sellerId) {
		this.sellerId = sellerId;
	}

}
