package neu.edu.entity;
// Generated Dec 15, 2016 5:29:54 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * SellerTable generated by hbm2java
 */
public class SellerTable implements java.io.Serializable {

	private int sellerId;
	private String usertype;
	private String username;
	private String password;
	private String status;
	private int personId;

	public SellerTable() {
	}

	public SellerTable(int sellerId, String usertype, String username, String password, String status, int personId) {
		this.sellerId = sellerId;
		this.usertype = usertype;
		this.username = username;
		this.password = password;
		this.status = status;
		this.personId = personId;
	}

	public int getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

}
